/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import data.Department;
import data.Region;
import data.Unit;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Nicolás Moreno
 */
public class GUI extends javax.swing.JFrame implements UI{
    
    private HashMap<String,Region> regions = new HashMap<>();
    
    private List<JButton> departmentsButtons = new ArrayList<>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
        //custom componenets
 
        
        
        MapPanel colombiaMap = new MapPanel();
        this.add(colombiaMap);
        colombiaMap.setBounds(0, 0, 650, 640);
        this.setSize(690, 690);
        colombiaMap.setVisible(true);
        colombiaMap.add(scenaryPanel);
        this.repaint();
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        scenaryPanel = new javax.swing.JPanel();
        guajira = new javax.swing.JButton();

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        scenaryPanel.setOpaque(false);

        guajira.setIcon(new ImageIcon("src/resources/assets/target.png"));
        guajira.setContentAreaFilled(false);
        guajira.setPreferredSize(new Dimension(30,30));
        guajira.setBorderPainted(false);

        javax.swing.GroupLayout scenaryPanelLayout = new javax.swing.GroupLayout(scenaryPanel);
        scenaryPanel.setLayout(scenaryPanelLayout);
        scenaryPanelLayout.setHorizontalGroup(
            scenaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenaryPanelLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(guajira)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        scenaryPanelLayout.setVerticalGroup(
            scenaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scenaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guajira)
                .addContainerGap(620, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public int selectUnit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Department selectDepartment() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void paintUnitInDepartment(Unit unit, Department department) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void printMap(HashMap<String, Region> map) {
        this.regions = map;
        
        //assosiate buttons with departments. 
        regions.get("Caribe").getDepartments().get("Guajira").setUiButton(guajira);
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guajira;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JPanel scenaryPanel;
    // End of variables declaration//GEN-END:variables

    
    private MapPanel colombianMap;
    
    public class MapPanel extends JPanel{
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            try {
                Image colombiaMap =  ImageIO.read(new File("src\\resources\\country\\Colombia2.png"));
                g.drawImage(colombiaMap, 0, 0, null);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
}
